# Fichier de configuration pour Netlify

# Section pour les redirections et réécritures
[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/a-propos"
  to = "/a-propos.html"
  status = 200